import ChangesDisplay from '@/components/ChangesDisplay';
import fs from 'fs/promises';
import path from 'path';

const BRANCHES = ['lineage-22.2', 'lineage-23.1'];

async function getAllBranchesData() {
  const allData: Record<string, any> = {};
  
  for (const branch of BRANCHES) {
    try {
      const filePath = path.join(process.cwd(), `public/data/${branch}.json`);
      const fileContents = await fs.readFile(filePath, 'utf8');
      allData[branch] = JSON.parse(fileContents);
    } catch (error) {
      console.error(`Error reading ${branch} data:`, error);
      allData[branch] = null;
    }
  }
  
  return allData;
}

export default async function Home() {
  const branchesData = await getAllBranchesData();

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      <div className="container mx-auto px-4 py-8">
        <header className="text-center mb-12">
          <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4 bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-500">
            LineageOS Source Tracker
          </h1>
          <p className="text-slate-300 text-base sm:text-lg">
            Track recent changes across LineageOS repositories
          </p>
        </header>

        <ChangesDisplay branchesData={branchesData} />

        <footer className="text-center text-slate-500 mt-16 pb-8 text-sm">
          <p>Auto-generated by GitHub Actions • Updated every 24 hours</p>
        </footer>
      </div>
    </main>
  );
}
