import ChangesDisplay from '@/components/ChangesDisplay';
import fs from 'fs/promises';
import path from 'path';

async function getChangesData() {
  try {
    const filePath = path.join(process.cwd(), 'public/data/changes.json');
    const fileContents = await fs.readFile(filePath, 'utf8');
    return JSON.parse(fileContents);
  } catch (error) {
    console.error('Error reading changes data:', error);
    return null;
  }
}

export default async function Home() {
  const data = await getChangesData();

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      <div className="container mx-auto px-4 py-8">
        <header className="text-center mb-12">
          <h1 className="text-5xl font-bold text-white mb-4 bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-500">
            LineageOS Source Tracker
          </h1>
          <p className="text-slate-300 text-lg">
            Track recent changes across LineageOS repositories
          </p>
        </header>

        {data ? (
          <ChangesDisplay data={data} />
        ) : (
          <div className="text-center text-slate-400 py-20">
            <p className="text-xl">No data available. Please run the sync script first.</p>
          </div>
        )}

        <footer className="text-center text-slate-500 mt-16 pb-8">
          <p>Auto-generated by GitHub Actions • Updated every 24 hours</p>
        </footer>
      </div>
    </main>
  );
}
