import ChangesDisplay from '@/components/ChangesDisplay';
import fs from 'fs/promises';
import path from 'path';

interface RomConfig {
  roms: Array<{
    id: string;
    displayName: string;
    branches: Array<{
      id: string;
      displayName: string;
      dataPath: string;
    }>;
  }>;
}

async function getRomConfig(): Promise<RomConfig | null> {
  try {
    const configPath = path.join(process.cwd(), 'public/rom-config.json');
    const configContent = await fs.readFile(configPath, 'utf8');
    return JSON.parse(configContent);
  } catch (error) {
    console.error('Error reading ROM config:', error);
    return null;
  }
}

async function loadAllData(config: RomConfig) {
  const allData: Record<string, any> = {};
  
  for (const rom of config.roms) {
    for (const branch of rom.branches) {
      const key = `${rom.id}/${branch.id}`;
      
      try {
        const filePath = path.join(process.cwd(), `public/data/${branch.dataPath}`);
        const fileContents = await fs.readFile(filePath, 'utf8');
        const data = JSON.parse(fileContents);
        
        allData[key] = {
          ...data,
          romDisplayName: rom.displayName,
          branchDisplayName: branch.displayName
        };
      } catch (error) {
        console.error(`Error reading ${key} data:`, error);
        allData[key] = null;
      }
    }
  }
  
  return allData;
}

export default async function Home() {
  const config = await getRomConfig();
  
  if (!config || config.roms.length === 0) {
    return (
      <main className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 flex items-center justify-center">
        <div className="text-center text-slate-400">
          <p className="text-xl">No ROM configuration found. Please run the data generation script first.</p>
        </div>
      </main>
    );
  }
  
  const allData = await loadAllData(config);

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      <div className="container mx-auto px-4 py-8">
        <header className="text-center mb-12">
          <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4 bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-500">
            Android ROM Source Tracker
          </h1>
          <p className="text-slate-300 text-base sm:text-lg">
            Track recent changes across custom Android ROM repositories
          </p>
        </header>

        <ChangesDisplay config={config} allData={allData} />

        <footer className="text-center text-slate-500 mt-16 pb-8 text-sm">
          <p>Auto-generated by GitHub Actions • Updated every 3 days</p>
        </footer>
      </div>
    </main>
  );
}
