import os

web_dir = "web"
output_file = os.path.join(web_dir, "index.html")

html_files = [
    f for f in os.listdir(web_dir)
    if f.endswith(".html") and f != "index.html"
]

html_files.sort()  # Optional: sort alphabetically

with open(output_file, "w") as f:
    f.write("""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>📚 LineageOS Source Changes</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: sans-serif; background: #f4f4f4; padding: 2rem; }
    h1 { font-size: 1.8rem; }
    ul { list-style: none; padding: 0; }
    li { margin-bottom: 1rem; }
    a { font-size: 1.2rem; color: #0070f3; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <h1>📚 LineageOS Source Changes</h1>
  <ul>
""")
    for html_file in html_files:
        branch_name = html_file.replace(".html", "")
        f.write(f'    <li><a href="{html_file}">{branch_name}</a></li>\n')

    f.write("""  </ul>
  <p><em>Auto-generated by GitHub Actions.</em></p>
</body>
</html>""")
